spring:
  datasource:
    username:
    password:
    driver-class-name:
    url:
  jpa:
    hibernate:
      ddl-auto:
kafka:
  group-id:
  topic:
    merchant-details:
      receive:
      monitor:
    merchant-history:
      statistic:
statistic:
  cron: "0 0 * * * *"